stages:
  - test

test-ssh:
  stage: test
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
  script:
    - echo "EC2_HOST is: $EC2_HOST"
    - echo "EC2_USER is: $EC2_USER"
    - ssh -v $EC2_USER@$EC2_HOST "echo ✅ SSH works"
