stages:
  - test

test-ssh:
  stage: test
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
    - echo "EC2_HOST is: $EC2_HOST"
    - test -n "$EC2_HOST" || (echo "ERROR: EC2_HOST is not set" && exit 1)
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts 2>/dev/null || (echo "Failed to scan EC2_HOST" && exit 1)
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - ssh -v "$EC2_USER@$EC2_HOST" "echo ✅ SSH works" || (echo "SSH connection failed" && exit 1)
